### ISSUE TITLE
Not able to run the migration.

### ISSUE THREAD

**Issue by hemashree** [justin808/fat-code-refactoring-techniques#16]
Hi Justin,

I cloned your project,configure the database and run the bundle install. All went well, but when I tried to migrate the application I am getting the 'Load Error' message of unable to load the guard the file. The following shows tracing of error.

LoadError: cannot load such file -- guard/guard
/Library/Ruby/Gems/2.0.0/gems/guard-spork-1.5.0/lib/guard/spork.rb:2:in `require'
/Library/Ruby/Gems/2.0.0/gems/guard-spork-1.5.0/lib/guard/spork.rb:2:in `<top (required)>'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.9.3/lib/bundler/runtime.rb:85:in `require'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.9.3/lib/bundler/runtime.rb:85:in `rescue in block in require'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.9.3/lib/bundler/runtime.rb:68:in `block in require'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.9.3/lib/bundler/runtime.rb:61:in `each'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.9.3/lib/bundler/runtime.rb:61:in `require'
/Library/Ruby/Gems/2.0.0/gems/bundler-1.9.3/lib/bundler.rb:134:in `require'
/Users/hemashree/workspace/fat-code-refactoring-techniques/config/application.rb:11:in `<top (required)>'
/Users/hemashree/workspace/fat-code-refactoring-techniques/Rakefile:4:in `require'
/Users/hemashree/workspace/fat-code-refactoring-techniques/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)

and I tried to run the command 'guard' in the console, for that I am getting this...

13:04:20 - ERROR - Could not load 'guard/spork' or find class Guard::Spork
13:04:20 - ERROR - Error is: cannot load such file -- guard/guard
13:04:20 - ERROR - /Library/Ruby/Gems/2.0.0/gems/guard-spork-1.5.0/lib/guard/spork.rb:2:in `require'
> [#] /Library/Ruby/Gems/2.0.0/gems/guard-spork-1.5.0/lib/guard/spork.rb:2:in `<top (required)>'
> [#] /Library/Ruby/Gems/2.0.0/gems/guard-2.12.8/lib/guard/plugin_util.rb:105:in `require'
> [#] /Library/Ruby/Gems/2.0.0/gems/guard-2.12.8/lib/guard/plugin_util.rb:105:in `rescue in plugin_class'
> [#] /Library/Ruby/Gems/2.0.0/gems/guard-2.12.8/lib/guard/plugin_util.rb:97:in `plugin_class'
> [#] /Library/Ruby/Gems/2.0.0/gems/guard-2.12.8/lib/guard/plugin_util.rb:56:in `initialize_plugin'
> [#] /Library/Ruby/Gems/2.0.0/gems/guard-2.12.8/lib/guard/internals/plugins.rb:26:in `add'
> [#] /Library/Ruby/Gems/2.0.0/gems/guard-2.12.8/lib/guard/dsl.rb:185:in `block in guard'
> [#] /Library/Ruby/Gems/2.0.0/gems/guard-2.12.8/lib/guard/dsl.rb:182:in `each'
> [#] /Library/Ruby/Gems/2.0.0/gems/guard-2.12.8/lib/guard/dsl.rb:182:in `guard'
> [#] /Users/hemashree/workspace/fat-code-refactoring-techniques/Guardfile:5:in `evaluate'
> [#] /Library/Ruby/Gems/2.0.0/gems/guard-2.12.8/lib/guard/dsl.rb:377:in `instance_eval'
> [#] /Library/Ruby/Gems/2.0.0/gems/guard-2.12.8/lib/guard/dsl.rb:377:in `evaluate'
> [#] /Library/Ruby/Gems/2.0.0/gems/guard-2.12.8/lib/guard/guardfile/evaluator.rb:91:in `evaluate'
> [#] /Library/Ruby/Gems/2.0.0/gems/guard-2.12.8/lib/guard.rb:134:in `_evaluate'
> [#] /Library/Ruby/Gems/2.0.0/gems/guard-2.12.8/lib/guard.rb:49:in `setup'
> [#] /Library/Ruby/Gems/2.0.0/gems/guard-2.12.8/lib/guard/commander.rb:32:in `start'
> [#] /Library/Ruby/Gems/2.0.0/gems/guard-2.12.8/lib/guard/cli/environments/valid.rb:16:in `start_guard'
> [#] /Library/Ruby/Gems/2.0.0/gems/guard-2.12.8/lib/guard/cli.rb:122:in `start'
> [#] /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
> [#] /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
> [#] /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
> [#] /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
> [#] /Library/Ruby/Gems/2.0.0/gems/guard-2.12.8/lib/guard/aruba_adapter.rb:32:in `execute'
> [#] /Library/Ruby/Gems/2.0.0/gems/guard-2.12.8/lib/guard/aruba_adapter.rb:19:in `execute!'

**Comment by justin808** [comment]
I'd get rid of any references to spork.

If you want to submit a PR with updated gems, please do so!
